spring.application.name=shop-backend-

#Connexion \u00c3\u00a0 PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=RoverAdmin
spring.datasource.driver-class-name=org.postgresql.Driver

#configuration Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect